/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DealScoreResponse {
  'fairValue' : bigint,
  'expectedDaysToSell' : bigint,
  'demandScore' : bigint,
  'liquidityScore' : bigint,
  'dealTag' : string,
  'priceGap' : bigint,
  'dealScore' : bigint,
}
export interface Enquiry {
  'id' : bigint,
  'projectName' : string,
  'name' : string,
  'createdAt' : Time,
  'projectId' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface ForecastResponse {
  'conservative' : bigint,
  'aggressive' : bigint,
  'realistic' : bigint,
  'disclaimer' : string,
  'basePrice' : bigint,
  'growthRate' : bigint,
}
export type ListingStatus = { 'published' : null } |
  { 'draft' : null };
export interface LocalityIntelligence {
  'amenitiesScore' : bigint,
  'city' : string,
  'name' : string,
  'avgPricePerSqft' : bigint,
  'demandScore' : bigint,
  'infraScore' : bigint,
  'locationScore' : bigint,
  'rentalPerSqft' : bigint,
  'growthRate' : bigint,
  'supplyDensity' : bigint,
}
export interface PropertyListing {
  'id' : bigint,
  'bhk' : bigint,
  'floor' : bigint,
  'status' : ListingStatus,
  'totalFloors' : bigint,
  'title' : string,
  'projectName' : string,
  'propertyType' : PropertyType,
  'city' : string,
  'createdAt' : Time,
  'badges' : Array<string>,
  'carpetArea' : bigint,
  'builderName' : string,
  'builtUpArea' : bigint,
  'description' : string,
  'openParking' : bigint,
  'legalStatus' : string,
  'mediaBlobs' : Array<ExternalBlob>,
  'coveredParking' : bigint,
  'buildingAge' : bigint,
  'sellerId' : Principal,
  'balconies' : bigint,
  'price' : bigint,
  'facing' : string,
  'location' : string,
  'plotArea' : bigint,
  'reraNumber' : string,
  'landUse' : string,
  'plotUnit' : string,
}
export type PropertyType = { 'villa' : null } |
  { 'flat' : null } |
  { 'plot' : null };
export interface RentalResponse {
  'avgRentPerSqft' : bigint,
  'yieldPercent' : bigint,
  'avgRent' : bigint,
  'rentMax' : bigint,
  'rentMin' : bigint,
  'rentalConfidence' : bigint,
  'vacancyRate' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'city' : string,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
  'panNumber' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValuationBreakdown {
  'comparablesUsed' : bigint,
  'pricePerSqft' : bigint,
  'infraContribution' : bigint,
  'locationContribution' : bigint,
  'demandContribution' : bigint,
  'comparablesContribution' : bigint,
}
export interface ValuationReport {
  'id' : bigint,
  'propertyType' : PropertyType,
  'userId' : Principal,
  'createdAt' : Time,
  'estimatedMax' : bigint,
  'estimatedMin' : bigint,
  'confidence' : bigint,
  'location' : string,
}
export interface ValuationResponse {
  'breakdown' : ValuationBreakdown,
  'confidenceReason' : string,
  'bestPrice' : bigint,
  'priceMax' : bigint,
  'priceMin' : bigint,
  'confidence' : bigint,
  'localityFound' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addValuationReport' : ActorMethod<
    [string, PropertyType, bigint, bigint, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'computeValuation' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    ValuationResponse
  >,
  'createEnquiry' : ActorMethod<[string, string, string, string], bigint>,
  'createListing' : ActorMethod<
    [
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      Array<ExternalBlob>,
      string,
    ],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'filterListings' : ActorMethod<
    [PropertyType, bigint, bigint, bigint],
    Array<PropertyListing>
  >,
  'getAllPublishedListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDealScore' : ActorMethod<[bigint], DealScoreResponse>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getFeedbackCount' : ActorMethod<[], bigint>,
  'getForecast' : ActorMethod<[string, string], ForecastResponse>,
  'getListingById' : ActorMethod<[bigint], [] | [PropertyListing]>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<PropertyListing>>,
  'getLocalityIntelligence' : ActorMethod<
    [string],
    [] | [LocalityIntelligence]
  >,
  'getLocalityList' : ActorMethod<[], Array<string>>,
  'getRentalIntelligence' : ActorMethod<[string], RentalResponse>,
  'getSavedProperties' : ActorMethod<[], Array<PropertyListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValuationReportsForUser' : ActorMethod<
    [Principal],
    Array<ValuationReport>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isIntelligenceSeeded' : ActorMethod<[], boolean>,
  'publishListing' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProperty' : ActorMethod<[bigint], undefined>,
  'searchListings' : ActorMethod<[string], Array<PropertyListing>>,
  'searchLocalities' : ActorMethod<[string], Array<string>>,
  'seedIntelligenceData' : ActorMethod<[], undefined>,
  'trackFeedback' : ActorMethod<[bigint, string], undefined>,
  'unsaveProperty' : ActorMethod<[bigint], undefined>,
  'updateListing' : ActorMethod<
    [
      bigint,
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      Array<ExternalBlob>,
      string,
    ],
    undefined
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];