/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PropertyType = IDL.Variant({
  'villa' : IDL.Null,
  'flat' : IDL.Null,
  'plot' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ValuationBreakdown = IDL.Record({
  'comparablesUsed' : IDL.Nat,
  'pricePerSqft' : IDL.Nat,
  'infraContribution' : IDL.Nat,
  'locationContribution' : IDL.Nat,
  'demandContribution' : IDL.Nat,
  'comparablesContribution' : IDL.Nat,
});
export const ValuationResponse = IDL.Record({
  'breakdown' : ValuationBreakdown,
  'confidenceReason' : IDL.Text,
  'bestPrice' : IDL.Nat,
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
  'confidence' : IDL.Nat,
  'localityFound' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'bhk' : IDL.Nat,
  'floor' : IDL.Nat,
  'status' : ListingStatus,
  'totalFloors' : IDL.Nat,
  'title' : IDL.Text,
  'projectName' : IDL.Text,
  'propertyType' : PropertyType,
  'city' : IDL.Text,
  'createdAt' : Time,
  'badges' : IDL.Vec(IDL.Text),
  'carpetArea' : IDL.Nat,
  'builderName' : IDL.Text,
  'builtUpArea' : IDL.Nat,
  'description' : IDL.Text,
  'openParking' : IDL.Nat,
  'legalStatus' : IDL.Text,
  'mediaBlobs' : IDL.Vec(ExternalBlob),
  'coveredParking' : IDL.Nat,
  'buildingAge' : IDL.Nat,
  'sellerId' : IDL.Principal,
  'balconies' : IDL.Nat,
  'price' : IDL.Nat,
  'facing' : IDL.Text,
  'location' : IDL.Text,
  'plotArea' : IDL.Nat,
  'reraNumber' : IDL.Text,
  'landUse' : IDL.Text,
  'plotUnit' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'city' : IDL.Text,
  'role' : UserRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'panNumber' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DealScoreResponse = IDL.Record({
  'fairValue' : IDL.Nat,
  'expectedDaysToSell' : IDL.Nat,
  'demandScore' : IDL.Nat,
  'liquidityScore' : IDL.Nat,
  'dealTag' : IDL.Text,
  'priceGap' : IDL.Int,
  'dealScore' : IDL.Nat,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'projectName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'projectId' : IDL.Text,
  'phone' : IDL.Text,
});
export const ForecastResponse = IDL.Record({
  'conservative' : IDL.Nat,
  'aggressive' : IDL.Nat,
  'realistic' : IDL.Nat,
  'disclaimer' : IDL.Text,
  'basePrice' : IDL.Nat,
  'growthRate' : IDL.Nat,
});
export const LocalityIntelligence = IDL.Record({
  'amenitiesScore' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'avgPricePerSqft' : IDL.Nat,
  'demandScore' : IDL.Nat,
  'infraScore' : IDL.Nat,
  'locationScore' : IDL.Nat,
  'rentalPerSqft' : IDL.Nat,
  'growthRate' : IDL.Nat,
  'supplyDensity' : IDL.Nat,
});
export const RentalResponse = IDL.Record({
  'avgRentPerSqft' : IDL.Nat,
  'yieldPercent' : IDL.Nat,
  'avgRent' : IDL.Nat,
  'rentMax' : IDL.Nat,
  'rentMin' : IDL.Nat,
  'rentalConfidence' : IDL.Nat,
  'vacancyRate' : IDL.Nat,
});
export const ValuationReport = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : PropertyType,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'estimatedMax' : IDL.Nat,
  'estimatedMin' : IDL.Nat,
  'confidence' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addValuationReport' : IDL.Func(
      [IDL.Text, PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'computeValuation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [ValuationResponse],
      ['query'],
    ),
  'createEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterListings' : IDL.Func(
      [PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getAllPublishedListings' : IDL.Func(
      [],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDealScore' : IDL.Func([IDL.Nat], [DealScoreResponse], ['query']),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getFeedbackCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getForecast' : IDL.Func([IDL.Text, IDL.Text], [ForecastResponse], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(PropertyListing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getLocalityIntelligence' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LocalityIntelligence)],
      ['query'],
    ),
  'getLocalityList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRentalIntelligence' : IDL.Func([IDL.Text], [RentalResponse], ['query']),
  'getSavedProperties' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValuationReportsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ValuationReport)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isIntelligenceSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'publishListing' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProperty' : IDL.Func([IDL.Nat], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'searchLocalities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'seedIntelligenceData' : IDL.Func([], [], []),
  'trackFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unsaveProperty' : IDL.Func([IDL.Nat], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PropertyType = IDL.Variant({
    'villa' : IDL.Null,
    'flat' : IDL.Null,
    'plot' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ValuationBreakdown = IDL.Record({
    'comparablesUsed' : IDL.Nat,
    'pricePerSqft' : IDL.Nat,
    'infraContribution' : IDL.Nat,
    'locationContribution' : IDL.Nat,
    'demandContribution' : IDL.Nat,
    'comparablesContribution' : IDL.Nat,
  });
  const ValuationResponse = IDL.Record({
    'breakdown' : ValuationBreakdown,
    'confidenceReason' : IDL.Text,
    'bestPrice' : IDL.Nat,
    'priceMax' : IDL.Nat,
    'priceMin' : IDL.Nat,
    'confidence' : IDL.Nat,
    'localityFound' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'bhk' : IDL.Nat,
    'floor' : IDL.Nat,
    'status' : ListingStatus,
    'totalFloors' : IDL.Nat,
    'title' : IDL.Text,
    'projectName' : IDL.Text,
    'propertyType' : PropertyType,
    'city' : IDL.Text,
    'createdAt' : Time,
    'badges' : IDL.Vec(IDL.Text),
    'carpetArea' : IDL.Nat,
    'builderName' : IDL.Text,
    'builtUpArea' : IDL.Nat,
    'description' : IDL.Text,
    'openParking' : IDL.Nat,
    'legalStatus' : IDL.Text,
    'mediaBlobs' : IDL.Vec(ExternalBlob),
    'coveredParking' : IDL.Nat,
    'buildingAge' : IDL.Nat,
    'sellerId' : IDL.Principal,
    'balconies' : IDL.Nat,
    'price' : IDL.Nat,
    'facing' : IDL.Text,
    'location' : IDL.Text,
    'plotArea' : IDL.Nat,
    'reraNumber' : IDL.Text,
    'landUse' : IDL.Text,
    'plotUnit' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'city' : IDL.Text,
    'role' : UserRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'panNumber' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DealScoreResponse = IDL.Record({
    'fairValue' : IDL.Nat,
    'expectedDaysToSell' : IDL.Nat,
    'demandScore' : IDL.Nat,
    'liquidityScore' : IDL.Nat,
    'dealTag' : IDL.Text,
    'priceGap' : IDL.Int,
    'dealScore' : IDL.Nat,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'projectName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'projectId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ForecastResponse = IDL.Record({
    'conservative' : IDL.Nat,
    'aggressive' : IDL.Nat,
    'realistic' : IDL.Nat,
    'disclaimer' : IDL.Text,
    'basePrice' : IDL.Nat,
    'growthRate' : IDL.Nat,
  });
  const LocalityIntelligence = IDL.Record({
    'amenitiesScore' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'avgPricePerSqft' : IDL.Nat,
    'demandScore' : IDL.Nat,
    'infraScore' : IDL.Nat,
    'locationScore' : IDL.Nat,
    'rentalPerSqft' : IDL.Nat,
    'growthRate' : IDL.Nat,
    'supplyDensity' : IDL.Nat,
  });
  const RentalResponse = IDL.Record({
    'avgRentPerSqft' : IDL.Nat,
    'yieldPercent' : IDL.Nat,
    'avgRent' : IDL.Nat,
    'rentMax' : IDL.Nat,
    'rentMin' : IDL.Nat,
    'rentalConfidence' : IDL.Nat,
    'vacancyRate' : IDL.Nat,
  });
  const ValuationReport = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : PropertyType,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'estimatedMax' : IDL.Nat,
    'estimatedMin' : IDL.Nat,
    'confidence' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addValuationReport' : IDL.Func(
        [IDL.Text, PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'computeValuation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [ValuationResponse],
        ['query'],
      ),
    'createEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterListings' : IDL.Func(
        [PropertyType, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getAllPublishedListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDealScore' : IDL.Func([IDL.Nat], [DealScoreResponse], ['query']),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getFeedbackCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getForecast' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ForecastResponse],
        ['query'],
      ),
    'getListingById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PropertyListing)],
        ['query'],
      ),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getLocalityIntelligence' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LocalityIntelligence)],
        ['query'],
      ),
    'getLocalityList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRentalIntelligence' : IDL.Func([IDL.Text], [RentalResponse], ['query']),
    'getSavedProperties' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValuationReportsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ValuationReport)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isIntelligenceSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'publishListing' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProperty' : IDL.Func([IDL.Nat], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'searchLocalities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'seedIntelligenceData' : IDL.Func([], [], []),
    'trackFeedback' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unsaveProperty' : IDL.Func([IDL.Nat], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };